export const initialTexts = {
    vendedor: "",
    cedula: "",
    sector: "",
    calle: "",
    casa: '',
    municipioProvincia: "en Consuelo, Provincia San Pedro de Macorís",
    modelo: "",
    chasis: "",
    año: "",
    color: "",
    precio: "SETENTA Y SIETE MIL PESOS (RD$77,000.00)",
    dia: "22",
    mes: "Enero",
    añoletra: "Dos Mil Veinticinco",
    añonumero: "2025",
    garante: '',
    garantecedula: '',
    sectorgarante: '',
    callegarante: '',
    casagarante: '',
    fecharuta: '08 DE FEBRERO 2025',
    precioinicialletra: '',
    precioinicialnumero: '',
    porcientoletras: 'Tres por ciento',
    porcientonumeros: '3',
    cantidadmeses: 'dieciocho meses',
    preciointeres: 'dos mil cien ',
    preciointeresnumero: '2,100.00',
    fechadeinicioenletras: '8 del mes de Enero del Dos Mil Veinticinco',
    fechadeinicioennumeros: '08/01/2025',
    terminopagareenletras: '08 del mes de Julio del Dos Mil Veintiseis',
    terminopagareennumeros: '08/07/2026',
    fechadespacho: '25/01/2025',
    telefonovende: '',
    ocupacion: '',
    civil: '',
    salario: '',
    parentezco: '',
    trabajo: '',
    telefonogara: '',
    tipo: 'Motocicleta'
  };